name: Manage next release
on:
  push:
    branches: [ releases/next, rjuliano/ci-cd ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        required: true
        default: 'Test'
jobs:
  update_next_release:
    runs-on: ubuntu-latest
    steps:
    - name: Update git
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        ref: releases/next
        token: ${{ github.token }}
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        cd scripts
        bundle install
    - name: Update gradle.properties and CHANGELOG.md
      run: |
        bundle exec fastlane android next_version_pr
    - name: Check modified file content
      run: |
        cat ../gradle.properties
        git status

    
